import type {Metadata} from "next";
import localFont from "next/font/local";
import "./globals.css";

const inter = localFont({
    src: "./fonts/Inter.ttf",
    variable: "--Inter",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "LudoLex",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className={inter.className}>{children}</body>
        </html>
    )
}
